name: Update dataset

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 9-15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Update dataset
      run: |-
        python makedataset.py
    - name: Commit and push if changed
      run: |-
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/outputs/
        git commit -m "Updated dataset" || exit 0
        git push